#!/bin/bash

cmake \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
      -DCMAKE_CXX_COMPILER=mpicxx \
      -DCMAKE_C_COMPILER=mpicc \
      -DCMAKE_Fortran_COMPILER=mpifort \
      -DPELEC_ENABLE_CUDA=ON \
      -DMPIEXEC_PREFLAGS=--oversubscribe \
      -DPELEC_DIM=3 \
      -DPELEC_ENABLE_MPI=ON \
      -DPELEC_ENABLE_AMREX_EB=ON \
      -DPELEC_ENABLE_TESTS=OFF \
      -DPELEC_ENABLE_MASA=OFF \
      -DPELEC_ENABLE_FCOMPARE:BOOL=OFF \
      -DPELEC_ENABLE_FCOMPARE_FOR_TESTS:BOOL=OFF \
      -DPELEC_ENABLE_DOCUMENTATION=OFF \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DAMREX_HOME_DIR=${AMREX_HOME} \
      -DPELE_PHYSICS_HOME_DIR=${PELE_PHYSICS_HOME} \
      ..
